trigger:
- main

pool:
  vmImage: 'ubuntu-latest'

jobs:
- job: CloneGitHubRepo
  displayName: 'Clone GitHub Repo'
  steps:
  - script: |
      git clone https://github.com/wowdevops014/lab-repo.git $(Build.ArtifactStagingDirectory)/lab-repo
    displayName: 'Clone GitHub Repository'

- job: Build
  displayName: 'Build'
  dependsOn: CloneGitHubRepo
  steps:
  - script: |
      # Your build commands go here
      cd $(Build.ArtifactStagingDirectory)/lab-repo
      # Example: npm install, dotnet build, etc.
    displayName: 'Build'

# Add additional jobs and steps as needed for your specific build process.
